# Add a line that has the commonName = pathToWhereItShouldGo
[FILES]
ReportTool-test = /opt/tarpontest/ReportTool-test
activemq = /opt/activemq

[RPMS]
httpd = apr, apr-util, httpd-tools, httpd, mod_ssl
postgresql = libpq,postgresql-13,postgresql-server-13,postgresql-contrib-13

[ACTIONS]
